name: 'Deploy OpenTelemetry'
on:
  push:
    branches: main
    paths:
      - .github/workflows/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: otel-deploy-job
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: http://172.183.157.184:8080
        with:
          secrets_to_redact: ${{ toJSON(secrets) }}
      - uses: plengauer/opentelemetry-github/actions/instrument/deploy@6448880258e9a9ae7c103f818a2a48a8479da842
        with:
          github_token: '${{ secrets.DEPLOY_OBSERVABILITY_TOKEN }}' # TODO configure a token that has permissions to push contents and open pull requests
          job_level_instrumentation_secret_redaction_strategy: all
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: http://172.183.157.184:8080
    permissions:
      actions: read
